services:
  postgres:
    image: 'postgres:alpine3.20'
    environment:
      - 'POSTGRES_DB=taskhandler'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=postgres'
    ports:
      - 5432:5432
